In [19]:
from __future__ import division, print_function
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
plt.rcParams['image.cmap'] = 'gist_earth'
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"
from tf_unet import image_gen
from tf_unet import unet
from tf_unet import util, image_util
from PIL import Image
from tensorflow.python.client import device_lib
print (device_lib.list_local_devices())


data_provider = image_util.NoduleDataProvider('tifdata/*.tif', 'validation_set/*.tif', 
                                              n_class=2, downsample = 0.5)

net = unet.Unet(layers=3, features_root=4, channels=1, n_class=2, gpu_ratio=1, cost = "dice_coefficient")

2018-05-16 11:37:18,598 Layers 3, features 4, filter size 3x3, pool size: 2x2


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 5816070582958964501
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6293720269
locality {
  bus_id: 1
  links {
  }
}
incarnation: 12113431599162531742
physical_device_desc: "device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0, compute capability: 6.1"
]


In [20]:
trainer = unet.Trainer(net, batch_size=4, gpu_ratio=1)
path = trainer.train(data_provider, 'output_data', training_iters=5, epochs=10)

2018-05-16 11:37:20,410 Removing '/home/msekni/day2/stage1/prediction'
2018-05-16 11:37:20,413 Removing '/home/msekni/day2/stage1/output_data'
2018-05-16 11:37:20,414 Allocating '/home/msekni/day2/stage1/prediction'
2018-05-16 11:37:20,414 Allocating '/home/msekni/day2/stage1/output_data'


(34, 512, 512, 1)


2018-05-16 11:37:22,098 Verification error= 99.8%, loss= -0.6187
2018-05-16 11:37:24,150 Start optimization
2018-05-16 11:37:25,151 Iter 0, Minibatch Loss= -0.6132, Training Accuracy= 0.9988, Minibatch error= 0.1%
2018-05-16 11:37:25,530 Iter 1, Minibatch Loss= -0.7010, Training Accuracy= 0.9981, Minibatch error= 0.2%
2018-05-16 11:37:25,901 Iter 2, Minibatch Loss= -0.8087, Training Accuracy= 0.9986, Minibatch error= 0.1%
2018-05-16 11:37:26,245 Iter 3, Minibatch Loss= -0.7692, Training Accuracy= 0.9962, Minibatch error= 0.4%
2018-05-16 11:37:26,531 Iter 4, Minibatch Loss= -0.5469, Training Accuracy= 0.9994, Minibatch error= 0.1%
2018-05-16 11:37:26,532 Epoch 0, Average loss: nan, learning rate: 0.2000
2018-05-16 11:37:27,255 Verification error= 0.2%, loss= -0.6230
/home/msekni/day2/stage1/tf_unet/util.py:74: RuntimeWarning: invalid value encountered in true_divide
  img /= np.amax(img)
2018-05-16 11:37:29,598 Iter 5, Minibatch Loss= -0.6403, Training Accuracy= 0.9976, Minibatch error=

In [ ]:
n_points = 4
data, label = data_provider(n_points)

data.shape

n_points = 4
data, label = data_provider(n_points, verification = False)

data.shape


fig, ax = plt.subplots(1,2, sharey=True, figsize=(8,4))
ax[0].imshow(data[0,...,0], aspect="auto")
ax[1].imshow(label[0,:,:,1], aspect="auto")

label.shape


In [39]:
import numpy as np



a = np.asarray([[3,3,3],[4,5,6], [7,8,9] ])
np.savetxt("foo.csv", a, delimiter=",")


In [4]:
from numpy import genfromtxt
my_data = genfromtxt('validation_loss.csv', delimiter=',')

In [5]:
my_data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [23]:
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [24]:
newrow = [7,2,3]
a = np.vstack([a, newrow])
a

array([[1, 2, 3],
       [3, 4, 5],
       [7, 2, 3]])

In [32]:
import os
if os.path.isfile('foo.csv') :
    print(123)

123


In [36]:
a = np.array((3,1))

In [37]:
a

array([3, 1])

In [35]:
newrow = [7,2,3]
a = np.vstack([a, newrow])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [2]:
import numpy as np

In [5]:
b = np.zeros((3,3,1))

In [12]:
a = np.ones((3,3,2))

In [13]:
c = np.concatenate((a,b), axis = -1)

In [14]:
c.shape


(3, 3, 3)

In [36]:
d=c[:,:,2]

In [38]:
d.shape

(3, 3)